// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace CaptainHook.Api.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    [Newtonsoft.Json.JsonObject("CaptainHook.Contract.AuthenticationDto")]
    public partial class CaptainHookContractAuthenticationDto
    {
        /// <summary>
        /// Initializes a new instance of the
        /// CaptainHookContractAuthenticationDto class.
        /// </summary>
        public CaptainHookContractAuthenticationDto()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// CaptainHookContractAuthenticationDto class.
        /// </summary>
        public CaptainHookContractAuthenticationDto(string type = default(string))
        {
            Type = type;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "type")]
        public string Type { get; set; }

    }
}
