// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace CaptainHook.Api.Client.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    [Newtonsoft.Json.JsonObject("CaptainHook.Contract.OidcAuthenticationDto")]
    public partial class CaptainHookContractOidcAuthenticationDto : CaptainHookContractAuthenticationDto
    {
        /// <summary>
        /// Initializes a new instance of the
        /// CaptainHookContractOidcAuthenticationDto class.
        /// </summary>
        public CaptainHookContractOidcAuthenticationDto()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// CaptainHookContractOidcAuthenticationDto class.
        /// </summary>
        public CaptainHookContractOidcAuthenticationDto(string type = default(string), string clientId = default(string), string uri = default(string), string clientSecretKeyName = default(string), IList<string> scopes = default(IList<string>))
            : base(type)
        {
            ClientId = clientId;
            Uri = uri;
            ClientSecretKeyName = clientSecretKeyName;
            Scopes = scopes;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "clientId")]
        public string ClientId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "uri")]
        public string Uri { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "clientSecretKeyName")]
        public string ClientSecretKeyName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "scopes")]
        public IList<string> Scopes { get; set; }

    }
}
