// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace CaptainHook.Api.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class CaptainHookApiModelsRefreshConfigRequest
    {
        /// <summary>
        /// Initializes a new instance of the
        /// CaptainHookApiModelsRefreshConfigRequest class.
        /// </summary>
        public CaptainHookApiModelsRefreshConfigRequest()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// CaptainHookApiModelsRefreshConfigRequest class.
        /// </summary>
        public CaptainHookApiModelsRefreshConfigRequest(string eventName = default(string))
        {
            EventName = eventName;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "eventName")]
        public string EventName { get; set; }

    }
}
