// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace CaptainHook.Api.Client.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class CaptainHookContractAuthenticationDto
    {
        /// <summary>
        /// Initializes a new instance of the
        /// CaptainHookContractAuthenticationDto class.
        /// </summary>
        public CaptainHookContractAuthenticationDto()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// CaptainHookContractAuthenticationDto class.
        /// </summary>
        public CaptainHookContractAuthenticationDto(string type = default(string), string clientId = default(string), string uri = default(string), CaptainHookContractClientSecretDto clientSecret = default(CaptainHookContractClientSecretDto), IList<string> scopes = default(IList<string>))
        {
            Type = type;
            ClientId = clientId;
            Uri = uri;
            ClientSecret = clientSecret;
            Scopes = scopes;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "type")]
        public string Type { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "clientId")]
        public string ClientId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "uri")]
        public string Uri { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "clientSecret")]
        public CaptainHookContractClientSecretDto ClientSecret { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "scopes")]
        public IList<string> Scopes { get; set; }

    }
}
