// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace CaptainHook.Api.Client.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class CaptainHookContractWebhooksDto
    {
        /// <summary>
        /// Initializes a new instance of the CaptainHookContractWebhooksDto
        /// class.
        /// </summary>
        public CaptainHookContractWebhooksDto()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CaptainHookContractWebhooksDto
        /// class.
        /// </summary>
        public CaptainHookContractWebhooksDto(string selectionRule = default(string), CaptainHookContractUriTransformDto uriTransform = default(CaptainHookContractUriTransformDto), IList<CaptainHookContractEndpointDto> endpoints = default(IList<CaptainHookContractEndpointDto>), string payloadTransform = default(string))
        {
            SelectionRule = selectionRule;
            UriTransform = uriTransform;
            Endpoints = endpoints;
            PayloadTransform = payloadTransform;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "selectionRule")]
        public string SelectionRule { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "uriTransform")]
        public CaptainHookContractUriTransformDto UriTransform { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "endpoints")]
        public IList<CaptainHookContractEndpointDto> Endpoints { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "payloadTransform")]
        public string PayloadTransform { get; set; }

    }
}
