// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace CaptainHook.Api.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class CaptainHookDomainResultsFailure
    {
        /// <summary>
        /// Initializes a new instance of the CaptainHookDomainResultsFailure
        /// class.
        /// </summary>
        public CaptainHookDomainResultsFailure()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CaptainHookDomainResultsFailure
        /// class.
        /// </summary>
        public CaptainHookDomainResultsFailure(string code = default(string), string message = default(string), string property = default(string))
        {
            Code = code;
            Message = message;
            Property = property;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "code")]
        public string Code { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "message")]
        public string Message { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "property")]
        public string Property { get; private set; }

    }
}
