// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace CaptainHook.Api.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    [Newtonsoft.Json.JsonObject("CaptainHook.Contract.BasicAuthenticationDto")]
    public partial class CaptainHookContractBasicAuthenticationDto : CaptainHookContractAuthenticationDto
    {
        /// <summary>
        /// Initializes a new instance of the
        /// CaptainHookContractBasicAuthenticationDto class.
        /// </summary>
        public CaptainHookContractBasicAuthenticationDto()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// CaptainHookContractBasicAuthenticationDto class.
        /// </summary>
        public CaptainHookContractBasicAuthenticationDto(string type = default(string), string username = default(string), string passwordKeyName = default(string))
            : base(type)
        {
            Username = username;
            PasswordKeyName = passwordKeyName;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "username")]
        public string Username { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "passwordKeyName")]
        public string PasswordKeyName { get; set; }

    }
}
